name: stack_device_info_service
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  device_info_plus: ^12.2.0
  stack: 
    git:
      url: https://github.com/kekland/stack
      path: packages/stack
