name: stack_prefs
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.5.3
  flutter_secure_storage: ^10.0.0-beta.4

  stack: 
    git:
      url: https://github.com/kekland/stack
      path: packages/stack
