name: _
publish_to: none

environment:
  sdk: ^3.10.0

workspace:
  - example
  - stack
  - stack_ui
  - stack_theme
  - stack_assets
  - stack_ffi
  - utils/stack_mouse_cursor
  - utils/stack_multi_pane_container
  - utils/stack_window_manager
