name: stack_window_manager
description: Utilities for working with windows in Flutter.
version: 1.0.0
publish_to: none
resolution: workspace

environment: 
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
    
  stack:
  stack_ui:
