import 'package:stack_theme/stack_theme.dart';

List<String> generateThemeFromDescription(ThemeDescription description) {
  final lines = <String>[];

  lines.add('// GENERATED CODE - DO NOT MODIFY BY HAND');
  lines.add('// Generated by stack_theme. Please refer to the documentation for more information.');
  lines.add('');
  lines.add('import \'package:flutter/widgets.dart\';');
  lines.add('import \'package:stack_ui/stack_ui.dart\';');
  lines.add('');

  final blocks = <List<String>>[];

  blocks.add(_generateFinal(description));
  blocks.add(_generatePlatformEnum(description));
  blocks.add(_generateVariantEnum(description));
  blocks.add(_generateColors(description));
  blocks.add(_generateTypography(description));
  blocks.add(_generateShadows(description));
  blocks.add(_generateAnimations(description));
  blocks.add(_generateSizes(description));

  // Finalize lines by adding blocks
  final nonEmptyBlocks = blocks.where((block) => block.isNotEmpty).toList();
  for (var i = 0; i < nonEmptyBlocks.length; i++) {
    lines.addAll(nonEmptyBlocks[i]);
    if (i != nonEmptyBlocks.length - 1) lines.add('');
  }

  return lines;
}

String _capitalize(String input) => input.isEmpty ? input : '${input[0].toUpperCase()}${input.substring(1)}';

List<String> _generatePlatformEnum(ThemeDescription description) {
  final lines = <String>[];

  if (description.platforms.isEmpty) return lines;

  lines.add('enum ThemePlatform {');
  for (final platform in description.platforms) lines.add('  $platform,');
  lines.add('}');

  return lines;
}

List<String> _generateVariantEnum(ThemeDescription description) {
  final lines = <String>[];

  if (description.variants.isEmpty) return lines;

  lines.add('enum ThemeVariant {');
  for (final variant in description.variants) lines.add('  $variant,');
  lines.add('}');

  return lines;
}

final _baseTextStyleTemplate = '''class BaseTextStyle extends TextStyle {
  BaseTextStyle(TextStyle base, {super.package})
    : super(
        color: null,
        inherit: true,
        background: base.background,
        backgroundColor: base.backgroundColor,
        debugLabel: base.debugLabel,
        decoration: base.decoration,
        decorationColor: base.decorationColor,
        decorationStyle: base.decorationStyle,
        decorationThickness: base.decorationThickness,
        fontFamily: base.fontFamily,
        fontFamilyFallback: base.fontFamilyFallback,
        fontFeatures: base.fontFeatures,
        fontSize: base.fontSize,
        fontStyle: base.fontStyle,
        fontVariations: base.fontVariations,
        fontWeight: base.fontWeight,
        foreground: base.foreground,
        height: base.height,
        leadingDistribution: base.leadingDistribution,
        letterSpacing: base.letterSpacing,
        locale: base.locale,
        overflow: base.overflow,
        shadows: base.shadows,
        textBaseline: base.textBaseline,
        wordSpacing: base.wordSpacing,
      );
}
''';

List<String> _generateTypography(ThemeDescription description) {
  final lines = <String>[];

  lines.add(_baseTextStyleTemplate);

  for (final style in description.typography) {
    final className = '${_capitalize(style.name)}TextStyle';
    final baseClassName = '${className}Base';

    lines.add('class $baseClassName extends BaseTextStyle {');
    lines.add('  $baseClassName(');
    lines.add('    super.base, {');
    for (final color in style.colors) lines.add('    required this.${color.name},');
    lines.add('    super.package,');
    lines.add('  });');
    lines.add('');

    lines.add('  factory $baseClassName.generate(TextStyle base, AppColors colors) {');
    lines.add('    return $baseClassName(');
    lines.add('      base,');
    for (final color in style.colors) lines.add('      ${color.name}: base.copyWith(color: colors.${color.getter}),');
    lines.add('    );');
    lines.add('  }');

    if (style.colors.isNotEmpty) lines.add('');
    for (final color in style.colors) lines.add('  final TextStyle ${color.name};');

    lines.add('}');
    lines.add('');

    lines.add('class $className extends $baseClassName {');
    lines.add('  $className(');
    lines.add('    super.base, {');
    for (final color in style.colors) lines.add('    required super.${color.name},');
    for (final weight in style.weights) lines.add('    required this.${weight.name},');
    lines.add('    super.package,');
    lines.add('  });');

    final variants = style.weights.isNotEmpty ? style.weights.map((w) => w.name) : ['base'];
    final defaultVariant = variants.first;

    lines.add('');
    lines.add('  factory $className.generate({');
    for (final variant in variants) lines.add('    required TextStyle $variant,');
    lines.add('    required AppColors colors,');
    lines.add('  }) {');
    lines.add('    return $className(');
    lines.add('      $defaultVariant,');
    for (final color in style.colors)
      lines.add('      ${color.name}: $defaultVariant.copyWith(color: colors.${color.getter}),');
    for (final weight in style.weights)
      lines.add('      ${weight.name}: $baseClassName.generate(${weight.name}, colors),');
    lines.add('    );');
    lines.add('  }');

    if (style.weights.isNotEmpty) lines.add('');
    for (final weight in style.weights) lines.add('  final $baseClassName ${weight.name};');
    lines.add('}');
    lines.add('');
  }

  lines.add('typedef AppTypography = ({');
  for (final style in description.typography) {
    final className = '${_capitalize(style.name)}TextStyle';
    lines.add('  $className ${style.name},');
  }

  lines.add('});');
  lines.add('');
  lines.add('class AppTypographyGenerator {');
  lines.add('  static AppTypography generate(');
  lines.add('    AppColors colors, {');
  for (final style in description.typography) {
    if (style.weights.isEmpty) {
      lines.add('    required TextStyle ${style.name},');
    } else {
      for (final weight in style.weights) {
        lines.add('    required TextStyle ${style.name}${_capitalize(weight.name)},');
      }
    }
  }
  lines.add('    TextStyle? overrides,');
  lines.add('  }) {');
  lines.add('    return (');
  for (final style in description.typography) {
    final className = '${_capitalize(style.name)}TextStyle';
    if (style.weights.isEmpty) {
      lines.add('      ${style.name}: $className.generate(base: ${style.name}.merge(overrides), colors: colors),');
    } else {
      lines.add('      ${style.name}: $className.generate(');
      for (final weight in style.weights) {
        lines.add('        ${weight.name}: ${style.name}${_capitalize(weight.name)}.merge(overrides),');
      }
      lines.add('        colors: colors,');
      lines.add('      ),');
    }
  }
  lines.add('    );');
  lines.add('  }');
  lines.add('}');
  lines.add('');

  if (lines.isNotEmpty) lines.removeLast();
  return lines;
}

List<String> _generateColors(ThemeDescription description) {
  final typedefs = <String>[];
  final lines = <String>[];

  String _generateFor(ColorDescription color) {
    String type;

    if (color is LeafColorDescription) {
      type = 'Color';
    } else if (color is SurfaceColorDescription) {
      type = 'SurfaceColor';
    } else if (color is ActionableColorDescription) {
      type = 'ActionableColor';
    } else if (color is GroupColorDescription) {
      final typedefName = '${_capitalize(color.name)}Colors';

      typedefs.add('typedef $typedefName = ({');
      for (final child in color.children) {
        final childLine = _generateFor(child);
        typedefs.add('  $childLine,');
      }
      typedefs.add('});');
      typedefs.add('');

      type = typedefName;
    } else {
      throw Exception('Unknown ColorDescription type: ${color.runtimeType}');
    }

    type = color.isOptional ? '$type?' : type;
    final line = '$type ${color.name}';

    return line;
  }

  lines.add('typedef AppColors = ({');
  for (final color in description.colors) {
    final line = _generateFor(color);
    lines.add('  $line,');
  }

  lines.add('});');
  return [...typedefs, ...lines];
}

List<String> _generateShadows(ThemeDescription description) {
  final lines = <String>[];

  if (description.shadows.isEmpty) return lines;

  lines.add('typedef AppShadows = ({');
  for (final shadow in description.shadows) lines.add('  List<BoxShadow> ${shadow.name},');
  lines.add('});');

  return lines;
}

List<String> _generateAnimations(ThemeDescription description) {
  final lines = <String>[];

  if (description.animations.isEmpty) return lines;

  lines.add('typedef AppAnimations = ({');
  for (final animation in description.animations) lines.add('  AnimationStyle ${animation.name},');
  lines.add('});');

  return lines;
}

List<String> _generateSizes(ThemeDescription description) {
  final lines = <String>[];

  if (description.sizes.isEmpty) return lines;

  lines.add('typedef AppSizes = ({');
  for (final size in description.sizes) lines.add('  double ${size.name},');
  lines.add('});');

  return lines;
}

List<String> _generateFinal(ThemeDescription description) {
  final lines = <String>[];

  lines.add('typedef AppTheme = ({');
  lines.add('  Brightness brightness,');
  if (description.platforms.isNotEmpty) lines.add('  ThemePlatform platform,');
  if (description.variants.isNotEmpty) lines.add('  ThemeVariant variant,');
  if (description.colors.isNotEmpty) lines.add('  AppColors colors,');
  if (description.typography.isNotEmpty) lines.add('  AppTypography typography,');
  if (description.shadows.isNotEmpty) lines.add('  AppShadows shadows,');
  if (description.animations.isNotEmpty) lines.add('  AppAnimations animations,');
  if (description.sizes.isNotEmpty) lines.add('  AppSizes sizes,');
  lines.add('});');
  lines.add('');
  lines.add('class _InheritedAppTheme extends InheritedWidget {');
  lines.add('  const _InheritedAppTheme({');
  lines.add('    required this.theme,');
  lines.add('    required super.child,');
  lines.add('  });');
  lines.add('');
  lines.add(
    '  static AppTheme of(BuildContext context) => context.dependOnInheritedWidgetOfExactType<_InheritedAppTheme>()!.theme;',
  );
  lines.add('');
  lines.add('  final AppTheme theme;');
  lines.add('');
  lines.add('  @override');
  lines.add('  bool updateShouldNotify(covariant _InheritedAppTheme oldWidget) => theme != oldWidget.theme;');
  lines.add('}');
  lines.add('');
  lines.add('class InheritedAppTheme extends StatelessWidget {');
  lines.add('  const InheritedAppTheme({');
  lines.add('    super.key,');
  lines.add('    required this.theme,');
  lines.add('    required this.child,');
  lines.add('  });');
  lines.add('');
  lines.add('  final AppTheme theme;');
  lines.add('  final Widget child;');
  lines.add('');
  lines.add('  @override');
  lines.add('  Widget build(BuildContext context) {');
  lines.add('    return InheritedBrightness(');
  lines.add('      brightness: theme.brightness,');
  lines.add('      child: _InheritedAppTheme(theme: theme, child: child),');
  lines.add('    );');
  lines.add('  }');
  lines.add('}');
  lines.add('');
  lines.add('extension AppThemeContext on BuildContext {');
  lines.add('  AppTheme get theme => _InheritedAppTheme.of(this);');
  if (description.platforms.isNotEmpty) lines.add('  ThemePlatform get themePlatform => theme.platform;');
  if (description.variants.isNotEmpty) lines.add('  ThemeVariant get themeVariant => theme.variant;');
  if (description.colors.isNotEmpty) lines.add('  AppColors get colors => theme.colors;');
  if (description.typography.isNotEmpty) lines.add('  AppTypography get typography => theme.typography;');
  if (description.shadows.isNotEmpty) lines.add('  AppShadows get shadows => theme.shadows;');
  if (description.animations.isNotEmpty) lines.add('  AppAnimations get animations => theme.animations;');
  if (description.sizes.isNotEmpty) lines.add('  AppSizes get sizes => theme.sizes;');
  lines.add('}');
  lines.add('');
  if (description.variants.isNotEmpty) {
    lines.add('class VariantBuilder extends StatelessWidget {');
    lines.add('  const VariantBuilder({');
    lines.add('    super.key,');
    for (final variant in description.variants) lines.add('    required this.$variant,');
    lines.add('  });');
    lines.add('');
    for (final variant in description.variants) lines.add('  final WidgetBuilder $variant;');
    lines.add('');
    lines.add('  @override');
    lines.add('  Widget build(BuildContext context) {');
    lines.add('    final variant = context.themeVariant;');
    lines.add('    return switch(variant) {');
    for (final variant in description.variants) lines.add('      .$variant => $variant(context),');
    lines.add('    };');
    lines.add('  }');
    lines.add('}');
  }

  return lines;
}
