name: stack_ui
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_hooks: ^0.21.3+1
  signals: ^6.2.0
  signals_flutter: ^6.2.0
  signals_hooks: ^0.3.1
  
  # utils
  collection: ^1.19.1
  oklch: ^0.0.3
  vector_math: ^2.2.0

  stack: 
    git:
      url: https://github.com/kekland/stack
      path: packages/stack
