name: stack_geolocation_service
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  geolocator: ^14.0.2
  latlong2: ^0.9.1

  stack: 
    git:
      url: https://github.com/kekland/stack
      path: packages/stack

  stack_permissions_service:
    git:
      url: https://github.com/kekland/stack
      path: packages/stack_permissions_service
