import 'package:flutter/gestures.dart';
import 'package:flutter/widgets.dart';

Widget defaultGestureRegionDetectorBuilder(
  BuildContext context,
  HitTestBehavior behavior,
  Set<PointerDeviceKind>? supportedDevices,
  Widget child,
  VoidCallback? onTapStart,
  VoidCallback? onTapEnd,
  VoidCallback? onTap,
  GestureDragStartCallback? onHorizontalDragStart,
  GestureDragUpdateCallback? onHorizontalDragUpdate,
  GestureDragEndCallback? onHorizontalDragEnd,
  GestureDragCancelCallback? onHorizontalDragCancel,
  GestureDragDownCallback? onHorizontalDragDown,
  GestureDragStartCallback? onVerticalDragStart,
  GestureDragUpdateCallback? onVerticalDragUpdate,
  GestureDragEndCallback? onVerticalDragEnd,
  GestureDragCancelCallback? onVerticalDragCancel,
  GestureDragDownCallback? onVerticalDragDown,
  GestureDragStartCallback? onPanStart,
  GestureDragUpdateCallback? onPanUpdate,
  GestureDragEndCallback? onPanEnd,
  GestureDragCancelCallback? onPanCancel,
  GestureDragDownCallback? onPanDown,
) {
  return GestureDetector(
    behavior: behavior,
    onTap: onTap,
    supportedDevices: supportedDevices,
    onTapDown: onTap != null ? (_) => onTapStart?.call() : null,
    onTapUp: onTap != null ? (_) => onTapEnd?.call() : null,
    onTapCancel: onTapEnd,
    onHorizontalDragStart: onHorizontalDragStart,
    onHorizontalDragUpdate: onHorizontalDragUpdate,
    onHorizontalDragEnd: onHorizontalDragEnd,
    onHorizontalDragCancel: onHorizontalDragCancel,
    onHorizontalDragDown: onHorizontalDragDown,
    onVerticalDragStart: onVerticalDragStart,
    onVerticalDragUpdate: onVerticalDragUpdate,
    onVerticalDragEnd: onVerticalDragEnd,
    onVerticalDragCancel: onVerticalDragCancel,
    onVerticalDragDown: onVerticalDragDown,
    onPanStart: onPanStart,
    onPanUpdate: onPanUpdate,
    onPanEnd: onPanEnd,
    onPanCancel: onPanCancel,
    child: child,
  );
}
