// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by stack_assets

import 'package:flutter/widgets.dart';
import 'package:vector_graphics/vector_graphics.dart';

// ignore_for_file: non_constant_identifier_names, unused_import, unused_element, unused_element_parameter

import 'package:example/theme.g.dart';
import 'package:stack_ui/stack_ui.dart';

class Assets {
  const Assets();

  static const brandIcons = brandIconsAssets;
  static const icons = iconsAssets;
  static const photos = photosAssets;
}

const assets = (
  brandIcons: Assets.brandIcons,
  icons: Assets.icons,
  photos: Assets.photos,
);

class BrandIconsAssets {
  const BrandIconsAssets();

  static const appleBrand = AssetBytesLoader('assets/gen/brandIcons/apple.brand.vec');
  static const googleBrandFill = AssetBytesLoader('assets/gen/brandIcons/google.brand.fill.vec');
  static const googleBrand = AssetBytesLoader('assets/gen/brandIcons/google.brand.vec');
}

const brandIconsAssets = (
  appleBrand: BrandIconsAssets.appleBrand,
  googleBrandFill: BrandIconsAssets.googleBrandFill,
  googleBrand: BrandIconsAssets.googleBrand,
);

class LightCupertinoIconsAssets {
  const LightCupertinoIconsAssets();

  static const appleBrand = AssetBytesLoader('assets/gen/icons/cupertino/light/apple.brand.vec');
  static const googleBrandFill = AssetBytesLoader('assets/gen/icons/cupertino/light/google.brand.fill.vec');
  static const googleBrand = AssetBytesLoader('assets/gen/icons/cupertino/light/google.brand.vec');
}

const lightCupertinoIconsAssets = (
  appleBrand: LightCupertinoIconsAssets.appleBrand,
  googleBrandFill: LightCupertinoIconsAssets.googleBrandFill,
  googleBrand: LightCupertinoIconsAssets.googleBrand,
);

class DarkCupertinoIconsAssets {
  const DarkCupertinoIconsAssets();

  static const appleBrand = AssetBytesLoader('assets/gen/icons/cupertino/dark/apple.brand.vec');
  static const googleBrandFill = AssetBytesLoader('assets/gen/icons/cupertino/dark/google.brand.fill.vec');
  static const googleBrand = AssetBytesLoader('assets/gen/icons/cupertino/dark/google.brand.vec');
}

const darkCupertinoIconsAssets = (
  appleBrand: DarkCupertinoIconsAssets.appleBrand,
  googleBrandFill: DarkCupertinoIconsAssets.googleBrandFill,
  googleBrand: DarkCupertinoIconsAssets.googleBrand,
);

AssetBytesLoader _cupertinoIconsAssets_appleBrand_resolver({required Brightness brightness}) {
  return switch ((brightness)) {
    (.light) => assets.icons.cupertino.light.appleBrand,
    (.dark) => assets.icons.cupertino.dark.appleBrand,
  };
}

AssetBytesLoader _cupertinoIconsAssets_googleBrandFill_resolver({required Brightness brightness}) {
  return switch ((brightness)) {
    (.light) => assets.icons.cupertino.light.googleBrandFill,
    (.dark) => assets.icons.cupertino.dark.googleBrandFill,
  };
}

AssetBytesLoader _cupertinoIconsAssets_googleBrand_resolver({required Brightness brightness}) {
  return switch ((brightness)) {
    (.light) => assets.icons.cupertino.light.googleBrand,
    (.dark) => assets.icons.cupertino.dark.googleBrand,
  };
}

class CupertinoIconsAssets {
  const CupertinoIconsAssets();

  static const light = lightCupertinoIconsAssets;
  static const dark = darkCupertinoIconsAssets;
  static const appleBrand = _cupertinoIconsAssets_appleBrand_resolver;
  static const googleBrandFill = _cupertinoIconsAssets_googleBrandFill_resolver;
  static const googleBrand = _cupertinoIconsAssets_googleBrand_resolver;
}

const cupertinoIconsAssets = (
  light: CupertinoIconsAssets.light,
  dark: CupertinoIconsAssets.dark,
  appleBrand: CupertinoIconsAssets.appleBrand,
  googleBrandFill: CupertinoIconsAssets.googleBrandFill,
  googleBrand: CupertinoIconsAssets.googleBrand,
);

class LightMaterialIconsAssets {
  const LightMaterialIconsAssets();

  static const appleBrand = AssetBytesLoader('assets/gen/icons/material/light/apple.brand.vec');
  static const googleBrandFill = AssetBytesLoader('assets/gen/icons/material/light/google.brand.fill.vec');
  static const googleBrand = AssetBytesLoader('assets/gen/icons/material/light/google.brand.vec');
}

const lightMaterialIconsAssets = (
  appleBrand: LightMaterialIconsAssets.appleBrand,
  googleBrandFill: LightMaterialIconsAssets.googleBrandFill,
  googleBrand: LightMaterialIconsAssets.googleBrand,
);

class DarkMaterialIconsAssets {
  const DarkMaterialIconsAssets();

  static const appleBrand = AssetBytesLoader('assets/gen/icons/material/dark/apple.brand.vec');
  static const googleBrandFill = AssetBytesLoader('assets/gen/icons/material/dark/google.brand.fill.vec');
  static const googleBrand = AssetBytesLoader('assets/gen/icons/material/dark/google.brand.vec');
}

const darkMaterialIconsAssets = (
  appleBrand: DarkMaterialIconsAssets.appleBrand,
  googleBrandFill: DarkMaterialIconsAssets.googleBrandFill,
  googleBrand: DarkMaterialIconsAssets.googleBrand,
);

AssetBytesLoader _materialIconsAssets_appleBrand_resolver({required Brightness brightness}) {
  return switch ((brightness)) {
    (.light) => assets.icons.material.light.appleBrand,
    (.dark) => assets.icons.material.dark.appleBrand,
  };
}

AssetBytesLoader _materialIconsAssets_googleBrandFill_resolver({required Brightness brightness}) {
  return switch ((brightness)) {
    (.light) => assets.icons.material.light.googleBrandFill,
    (.dark) => assets.icons.material.dark.googleBrandFill,
  };
}

AssetBytesLoader _materialIconsAssets_googleBrand_resolver({required Brightness brightness}) {
  return switch ((brightness)) {
    (.light) => assets.icons.material.light.googleBrand,
    (.dark) => assets.icons.material.dark.googleBrand,
  };
}

class MaterialIconsAssets {
  const MaterialIconsAssets();

  static const light = lightMaterialIconsAssets;
  static const dark = darkMaterialIconsAssets;
  static const appleBrand = _materialIconsAssets_appleBrand_resolver;
  static const googleBrandFill = _materialIconsAssets_googleBrandFill_resolver;
  static const googleBrand = _materialIconsAssets_googleBrand_resolver;
}

const materialIconsAssets = (
  light: MaterialIconsAssets.light,
  dark: MaterialIconsAssets.dark,
  appleBrand: MaterialIconsAssets.appleBrand,
  googleBrandFill: MaterialIconsAssets.googleBrandFill,
  googleBrand: MaterialIconsAssets.googleBrand,
);

AssetBytesLoader _iconsAssets_appleBrand_resolver({required ThemePlatform platform, required Brightness brightness}) {
  return switch ((platform, brightness)) {
    (.cupertino, .light) => assets.icons.cupertino.light.appleBrand,
    (.material, .light) => assets.icons.material.light.appleBrand,
    (.cupertino, .dark) => assets.icons.cupertino.dark.appleBrand,
    (.material, .dark) => assets.icons.material.dark.appleBrand,
  };
}

AssetBytesLoader _iconsAssets_appleBrand_contextResolver(BuildContext context) {
  return _iconsAssets_appleBrand_resolver(
    platform: context.themePlatform,
    brightness: context.brightness,
  );
}

AssetBytesLoader _iconsAssets_googleBrandFill_resolver({required ThemePlatform platform, required Brightness brightness}) {
  return switch ((platform, brightness)) {
    (.cupertino, .light) => assets.icons.cupertino.light.googleBrandFill,
    (.material, .light) => assets.icons.material.light.googleBrandFill,
    (.cupertino, .dark) => assets.icons.cupertino.dark.googleBrandFill,
    (.material, .dark) => assets.icons.material.dark.googleBrandFill,
  };
}

AssetBytesLoader _iconsAssets_googleBrandFill_contextResolver(BuildContext context) {
  return _iconsAssets_googleBrandFill_resolver(
    platform: context.themePlatform,
    brightness: context.brightness,
  );
}

AssetBytesLoader _iconsAssets_googleBrand_resolver({required ThemePlatform platform, required Brightness brightness}) {
  return switch ((platform, brightness)) {
    (.cupertino, .light) => assets.icons.cupertino.light.googleBrand,
    (.material, .light) => assets.icons.material.light.googleBrand,
    (.cupertino, .dark) => assets.icons.cupertino.dark.googleBrand,
    (.material, .dark) => assets.icons.material.dark.googleBrand,
  };
}

AssetBytesLoader _iconsAssets_googleBrand_contextResolver(BuildContext context) {
  return _iconsAssets_googleBrand_resolver(
    platform: context.themePlatform,
    brightness: context.brightness,
  );
}

class IconsAssets {
  const IconsAssets();

  static const cupertino = cupertinoIconsAssets;
  static const material = materialIconsAssets;
  static const appleBrand = _iconsAssets_appleBrand_resolver;
  static const googleBrandFill = _iconsAssets_googleBrandFill_resolver;
  static const googleBrand = _iconsAssets_googleBrand_resolver;
}

const iconsAssets = (
  cupertino: IconsAssets.cupertino,
  material: IconsAssets.material,
  appleBrand: IconsAssets.appleBrand,
  googleBrandFill: IconsAssets.googleBrandFill,
  googleBrand: IconsAssets.googleBrand,
);

class PhotosAssets {
  const PhotosAssets();

  static const frame1 = AssetImage('assets/gen/photos/Frame 1.png');
  static const motionLogo = AssetImage('assets/gen/photos/motion logo.png');
  static const myText = 'assets/gen/photos/my_text.txt';
}

const photosAssets = (
  frame1: PhotosAssets.frame1,
  motionLogo: PhotosAssets.motionLogo,
  myText: PhotosAssets.myText,
);

class _BaseIcon extends StatelessWidget {
  const _BaseIcon.selector({
    super.key,
    required BytesLoader Function(BuildContext) loader,
    BytesLoader Function(BuildContext)? filledLoader,
    this.size,
    this.color,
    this.autocolor = true,
  }) : loader = null,
       filledLoader = null,
       loaderFn = loader,
       filledLoaderFn = filledLoader,
       isSelectorBased = true;

  const _BaseIcon.basic({
    super.key,
    required this.loader,
    this.filledLoader,
    this.size,
    this.color,
    this.autocolor = true,
  }) : loaderFn = null,
       filledLoaderFn = null,
       isSelectorBased = false;

  final BytesLoader Function(BuildContext)? loaderFn;
  final BytesLoader Function(BuildContext)? filledLoaderFn;
  final BytesLoader? loader;
  final BytesLoader? filledLoader;
  final bool isSelectorBased;
  final double? size;
  final Color? color;
  final bool autocolor;

  @override
  Widget build(BuildContext context) {
    final iconTheme = IconTheme.of(context);

    final color = this.color ?? iconTheme.color ?? Surface.maybeColorOf(context)?.foreground;
    final size = this.size ?? iconTheme.size ?? 24.0;
    final fill = iconTheme.fill ?? 0.0;

    Widget _buildIcon(BytesLoader loader, [double? opacity]) {
      return VectorGraphic(
        loader: loader,
        colorFilter: color != null && autocolor ? ColorFilter.mode(color, BlendMode.srcIn) : null,
        width: size,
        height: size,
        opacity: opacity != null ? AlwaysStoppedAnimation(opacity) : null,
      );
    }

    final loader = isSelectorBased ? loaderFn!(context) : this.loader!;
    final filledLoader = isSelectorBased ? filledLoaderFn?.call(context) : this.filledLoader;

    if (filledLoader != null) {
      return Stack(
        children: [
          _buildIcon(loader, 1.0 - fill),
          _buildIcon(filledLoader, fill),
        ],
      );
    } else {
      return _buildIcon(loader);
    }
  }
}

class BrandIcons extends _BaseIcon {
  const BrandIcons.appleBrand({super.key, super.size, super.color}) : super.basic(loader: BrandIconsAssets.appleBrand, filledLoader: null, autocolor: true);
  const BrandIcons.googleBrandFill({super.key, super.size, super.color}) : super.basic(loader: BrandIconsAssets.googleBrandFill, filledLoader: null, autocolor: false);
  const BrandIcons.googleBrand({super.key, super.size, super.color}) : super.basic(loader: BrandIconsAssets.googleBrand, filledLoader: BrandIconsAssets.googleBrandFill, autocolor: false);
}

class Icons extends _BaseIcon {
  const Icons.appleBrand({super.key, super.size, super.color}) : super.selector(loader: _iconsAssets_appleBrand_contextResolver, filledLoader: null, autocolor: true);
  const Icons.googleBrandFill({super.key, super.size, super.color}) : super.selector(loader: _iconsAssets_googleBrandFill_contextResolver, filledLoader: null, autocolor: false);
  const Icons.googleBrand({super.key, super.size, super.color}) : super.selector(loader: _iconsAssets_googleBrand_contextResolver, filledLoader: _iconsAssets_googleBrandFill_contextResolver, autocolor: false);
}
