// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by stack_theme. Please refer to the documentation for more information.

import 'package:flutter/widgets.dart';
import 'package:stack_ui/stack_ui.dart';

typedef AppTheme = ({
  Brightness brightness,
  ThemePlatform platform,
  ThemeVariant variant,
  AppColors colors,
  AppTypography typography,
  AppShadows shadows,
  AppAnimations animations,
});

class _InheritedAppTheme extends InheritedWidget {
  const _InheritedAppTheme({
    required this.theme,
    required super.child,
  });

  static AppTheme of(BuildContext context) => context.dependOnInheritedWidgetOfExactType<_InheritedAppTheme>()!.theme;

  final AppTheme theme;

  @override
  bool updateShouldNotify(covariant _InheritedAppTheme oldWidget) => theme != oldWidget.theme;
}

class InheritedAppTheme extends StatelessWidget {
  const InheritedAppTheme({
    super.key,
    required this.theme,
    required this.child,
  });

  final AppTheme theme;
  final Widget child;

  @override
  Widget build(BuildContext context) {
    return InheritedBrightness(
      brightness: theme.brightness,
      child: _InheritedAppTheme(theme: theme, child: child),
    );
  }
}

extension AppThemeContext on BuildContext {
  AppTheme get theme => _InheritedAppTheme.of(this);
  ThemePlatform get themePlatform => theme.platform;
  ThemeVariant get themeVariant => theme.variant;
  AppColors get colors => theme.colors;
  AppTypography get typography => theme.typography;
  AppShadows get shadows => theme.shadows;
  AppAnimations get animations => theme.animations;
}

class VariantBuilder extends StatelessWidget {
  const VariantBuilder({
    super.key,
    required this.purple,
    required this.orange,
  });

  final WidgetBuilder purple;
  final WidgetBuilder orange;

  @override
  Widget build(BuildContext context) {
    final variant = context.themeVariant;
    return switch(variant) {
      .purple => purple(context),
      .orange => orange(context),
    };
  }
}

enum ThemePlatform {
  material,
  cupertino,
}

enum ThemeVariant {
  purple,
  orange,
}

typedef BackgroundColors = ({
  Color primary,
  Color secondary,
});

typedef AccentColors = ({
  SurfaceColor primary,
  SurfaceColor secondary,
});

typedef DangerColors = ({
  SurfaceColor primary,
  SurfaceColor secondary,
});

typedef DisplayColors = ({
  Color primary,
  Color secondary,
  Color tertiary,
});

typedef ActionColors = ({
  ActionableColor primary,
  ActionableColor secondary,
  ActionableColor danger,
});

typedef OptionalsColors = ({
  Color? primary,
  Color? secondary,
});

typedef AppColors = ({
  BackgroundColors background,
  AccentColors accent,
  DangerColors danger,
  DisplayColors display,
  ActionColors action,
  OptionalsColors optionals,
});

class BaseTextStyle extends TextStyle {
  BaseTextStyle(TextStyle base, {super.package})
    : super(
        color: null,
        inherit: true,
        background: base.background,
        backgroundColor: base.backgroundColor,
        debugLabel: base.debugLabel,
        decoration: base.decoration,
        decorationColor: base.decorationColor,
        decorationStyle: base.decorationStyle,
        decorationThickness: base.decorationThickness,
        fontFamily: base.fontFamily,
        fontFamilyFallback: base.fontFamilyFallback,
        fontFeatures: base.fontFeatures,
        fontSize: base.fontSize,
        fontStyle: base.fontStyle,
        fontVariations: base.fontVariations,
        fontWeight: base.fontWeight,
        foreground: base.foreground,
        height: base.height,
        leadingDistribution: base.leadingDistribution,
        letterSpacing: base.letterSpacing,
        locale: base.locale,
        overflow: base.overflow,
        shadows: base.shadows,
        textBaseline: base.textBaseline,
        wordSpacing: base.wordSpacing,
      );
}

class SimpleTextStyleBase extends BaseTextStyle {
  SimpleTextStyleBase(
    super.base, {
    super.package,
  });

  factory SimpleTextStyleBase.generate(TextStyle base, AppColors colors) {
    return SimpleTextStyleBase(
      base,
    );
  }
}

class SimpleTextStyle extends SimpleTextStyleBase {
  SimpleTextStyle(
    super.base, {
    super.package,
  });

  factory SimpleTextStyle.generate({
    required TextStyle base,
    required AppColors colors,
  }) {
    return SimpleTextStyle(
      base,
    );
  }
}

class BrandTextStyleBase extends BaseTextStyle {
  BrandTextStyleBase(
    super.base, {
    super.package,
  });

  factory BrandTextStyleBase.generate(TextStyle base, AppColors colors) {
    return BrandTextStyleBase(
      base,
    );
  }
}

class BrandTextStyle extends BrandTextStyleBase {
  BrandTextStyle(
    super.base, {
    required this.regular,
    required this.bold,
    super.package,
  });

  factory BrandTextStyle.generate({
    required TextStyle regular,
    required TextStyle bold,
    required AppColors colors,
  }) {
    return BrandTextStyle(
      regular,
      regular: BrandTextStyleBase.generate(regular, colors),
      bold: BrandTextStyleBase.generate(bold, colors),
    );
  }

  final BrandTextStyleBase regular;
  final BrandTextStyleBase bold;
}

class LargeTitleTextStyleBase extends BaseTextStyle {
  LargeTitleTextStyleBase(
    super.base, {
    required this.primary,
    required this.secondary,
    required this.tertiary,
    required this.accent,
    required this.danger,
    super.package,
  });

  factory LargeTitleTextStyleBase.generate(TextStyle base, AppColors colors) {
    return LargeTitleTextStyleBase(
      base,
      primary: base.copyWith(color: colors.display.primary),
      secondary: base.copyWith(color: colors.display.secondary),
      tertiary: base.copyWith(color: colors.display.tertiary),
      accent: base.copyWith(color: colors.accent.primary),
      danger: base.copyWith(color: colors.danger.primary),
    );
  }

  final TextStyle primary;
  final TextStyle secondary;
  final TextStyle tertiary;
  final TextStyle accent;
  final TextStyle danger;
}

class LargeTitleTextStyle extends LargeTitleTextStyleBase {
  LargeTitleTextStyle(
    super.base, {
    required super.primary,
    required super.secondary,
    required super.tertiary,
    required super.accent,
    required super.danger,
    super.package,
  });

  factory LargeTitleTextStyle.generate({
    required TextStyle base,
    required AppColors colors,
  }) {
    return LargeTitleTextStyle(
      base,
      primary: base.copyWith(color: colors.display.primary),
      secondary: base.copyWith(color: colors.display.secondary),
      tertiary: base.copyWith(color: colors.display.tertiary),
      accent: base.copyWith(color: colors.accent.primary),
      danger: base.copyWith(color: colors.danger.primary),
    );
  }
}

class Title1TextStyleBase extends BaseTextStyle {
  Title1TextStyleBase(
    super.base, {
    required this.primary,
    required this.secondary,
    required this.tertiary,
    required this.accent,
    required this.danger,
    super.package,
  });

  factory Title1TextStyleBase.generate(TextStyle base, AppColors colors) {
    return Title1TextStyleBase(
      base,
      primary: base.copyWith(color: colors.display.primary),
      secondary: base.copyWith(color: colors.display.secondary),
      tertiary: base.copyWith(color: colors.display.tertiary),
      accent: base.copyWith(color: colors.accent.primary),
      danger: base.copyWith(color: colors.danger.primary),
    );
  }

  final TextStyle primary;
  final TextStyle secondary;
  final TextStyle tertiary;
  final TextStyle accent;
  final TextStyle danger;
}

class Title1TextStyle extends Title1TextStyleBase {
  Title1TextStyle(
    super.base, {
    required super.primary,
    required super.secondary,
    required super.tertiary,
    required super.accent,
    required super.danger,
    required this.regular,
    required this.bold,
    super.package,
  });

  factory Title1TextStyle.generate({
    required TextStyle regular,
    required TextStyle bold,
    required AppColors colors,
  }) {
    return Title1TextStyle(
      regular,
      primary: regular.copyWith(color: colors.display.primary),
      secondary: regular.copyWith(color: colors.display.secondary),
      tertiary: regular.copyWith(color: colors.display.tertiary),
      accent: regular.copyWith(color: colors.accent.primary),
      danger: regular.copyWith(color: colors.danger.primary),
      regular: Title1TextStyleBase.generate(regular, colors),
      bold: Title1TextStyleBase.generate(bold, colors),
    );
  }

  final Title1TextStyleBase regular;
  final Title1TextStyleBase bold;
}

class Title2TextStyleBase extends BaseTextStyle {
  Title2TextStyleBase(
    super.base, {
    required this.primary,
    required this.secondary,
    required this.tertiary,
    required this.accent,
    required this.danger,
    super.package,
  });

  factory Title2TextStyleBase.generate(TextStyle base, AppColors colors) {
    return Title2TextStyleBase(
      base,
      primary: base.copyWith(color: colors.display.primary),
      secondary: base.copyWith(color: colors.display.secondary),
      tertiary: base.copyWith(color: colors.display.tertiary),
      accent: base.copyWith(color: colors.accent.primary),
      danger: base.copyWith(color: colors.danger.primary),
    );
  }

  final TextStyle primary;
  final TextStyle secondary;
  final TextStyle tertiary;
  final TextStyle accent;
  final TextStyle danger;
}

class Title2TextStyle extends Title2TextStyleBase {
  Title2TextStyle(
    super.base, {
    required super.primary,
    required super.secondary,
    required super.tertiary,
    required super.accent,
    required super.danger,
    required this.regular,
    required this.bold,
    super.package,
  });

  factory Title2TextStyle.generate({
    required TextStyle regular,
    required TextStyle bold,
    required AppColors colors,
  }) {
    return Title2TextStyle(
      regular,
      primary: regular.copyWith(color: colors.display.primary),
      secondary: regular.copyWith(color: colors.display.secondary),
      tertiary: regular.copyWith(color: colors.display.tertiary),
      accent: regular.copyWith(color: colors.accent.primary),
      danger: regular.copyWith(color: colors.danger.primary),
      regular: Title2TextStyleBase.generate(regular, colors),
      bold: Title2TextStyleBase.generate(bold, colors),
    );
  }

  final Title2TextStyleBase regular;
  final Title2TextStyleBase bold;
}

class Subtitle1TextStyleBase extends BaseTextStyle {
  Subtitle1TextStyleBase(
    super.base, {
    required this.primary,
    required this.secondary,
    required this.tertiary,
    required this.accent,
    required this.danger,
    super.package,
  });

  factory Subtitle1TextStyleBase.generate(TextStyle base, AppColors colors) {
    return Subtitle1TextStyleBase(
      base,
      primary: base.copyWith(color: colors.display.primary),
      secondary: base.copyWith(color: colors.display.secondary),
      tertiary: base.copyWith(color: colors.display.tertiary),
      accent: base.copyWith(color: colors.accent.primary),
      danger: base.copyWith(color: colors.danger.primary),
    );
  }

  final TextStyle primary;
  final TextStyle secondary;
  final TextStyle tertiary;
  final TextStyle accent;
  final TextStyle danger;
}

class Subtitle1TextStyle extends Subtitle1TextStyleBase {
  Subtitle1TextStyle(
    super.base, {
    required super.primary,
    required super.secondary,
    required super.tertiary,
    required super.accent,
    required super.danger,
    required this.regular,
    required this.bold,
    super.package,
  });

  factory Subtitle1TextStyle.generate({
    required TextStyle regular,
    required TextStyle bold,
    required AppColors colors,
  }) {
    return Subtitle1TextStyle(
      regular,
      primary: regular.copyWith(color: colors.display.primary),
      secondary: regular.copyWith(color: colors.display.secondary),
      tertiary: regular.copyWith(color: colors.display.tertiary),
      accent: regular.copyWith(color: colors.accent.primary),
      danger: regular.copyWith(color: colors.danger.primary),
      regular: Subtitle1TextStyleBase.generate(regular, colors),
      bold: Subtitle1TextStyleBase.generate(bold, colors),
    );
  }

  final Subtitle1TextStyleBase regular;
  final Subtitle1TextStyleBase bold;
}

class Body1TextStyleBase extends BaseTextStyle {
  Body1TextStyleBase(
    super.base, {
    required this.primary,
    required this.secondary,
    required this.tertiary,
    required this.accent,
    required this.danger,
    super.package,
  });

  factory Body1TextStyleBase.generate(TextStyle base, AppColors colors) {
    return Body1TextStyleBase(
      base,
      primary: base.copyWith(color: colors.display.primary),
      secondary: base.copyWith(color: colors.display.secondary),
      tertiary: base.copyWith(color: colors.display.tertiary),
      accent: base.copyWith(color: colors.accent.primary),
      danger: base.copyWith(color: colors.danger.primary),
    );
  }

  final TextStyle primary;
  final TextStyle secondary;
  final TextStyle tertiary;
  final TextStyle accent;
  final TextStyle danger;
}

class Body1TextStyle extends Body1TextStyleBase {
  Body1TextStyle(
    super.base, {
    required super.primary,
    required super.secondary,
    required super.tertiary,
    required super.accent,
    required super.danger,
    required this.regular,
    required this.bold,
    super.package,
  });

  factory Body1TextStyle.generate({
    required TextStyle regular,
    required TextStyle bold,
    required AppColors colors,
  }) {
    return Body1TextStyle(
      regular,
      primary: regular.copyWith(color: colors.display.primary),
      secondary: regular.copyWith(color: colors.display.secondary),
      tertiary: regular.copyWith(color: colors.display.tertiary),
      accent: regular.copyWith(color: colors.accent.primary),
      danger: regular.copyWith(color: colors.danger.primary),
      regular: Body1TextStyleBase.generate(regular, colors),
      bold: Body1TextStyleBase.generate(bold, colors),
    );
  }

  final Body1TextStyleBase regular;
  final Body1TextStyleBase bold;
}

class Caption1TextStyleBase extends BaseTextStyle {
  Caption1TextStyleBase(
    super.base, {
    required this.primary,
    required this.secondary,
    required this.tertiary,
    required this.accent,
    required this.danger,
    super.package,
  });

  factory Caption1TextStyleBase.generate(TextStyle base, AppColors colors) {
    return Caption1TextStyleBase(
      base,
      primary: base.copyWith(color: colors.display.primary),
      secondary: base.copyWith(color: colors.display.secondary),
      tertiary: base.copyWith(color: colors.display.tertiary),
      accent: base.copyWith(color: colors.accent.primary),
      danger: base.copyWith(color: colors.danger.primary),
    );
  }

  final TextStyle primary;
  final TextStyle secondary;
  final TextStyle tertiary;
  final TextStyle accent;
  final TextStyle danger;
}

class Caption1TextStyle extends Caption1TextStyleBase {
  Caption1TextStyle(
    super.base, {
    required super.primary,
    required super.secondary,
    required super.tertiary,
    required super.accent,
    required super.danger,
    required this.regular,
    required this.bold,
    required this.black,
    super.package,
  });

  factory Caption1TextStyle.generate({
    required TextStyle regular,
    required TextStyle bold,
    required TextStyle black,
    required AppColors colors,
  }) {
    return Caption1TextStyle(
      regular,
      primary: regular.copyWith(color: colors.display.primary),
      secondary: regular.copyWith(color: colors.display.secondary),
      tertiary: regular.copyWith(color: colors.display.tertiary),
      accent: regular.copyWith(color: colors.accent.primary),
      danger: regular.copyWith(color: colors.danger.primary),
      regular: Caption1TextStyleBase.generate(regular, colors),
      bold: Caption1TextStyleBase.generate(bold, colors),
      black: Caption1TextStyleBase.generate(black, colors),
    );
  }

  final Caption1TextStyleBase regular;
  final Caption1TextStyleBase bold;
  final Caption1TextStyleBase black;
}

class Caption2TextStyleBase extends BaseTextStyle {
  Caption2TextStyleBase(
    super.base, {
    required this.primary,
    required this.secondary,
    required this.tertiary,
    required this.accent,
    required this.danger,
    super.package,
  });

  factory Caption2TextStyleBase.generate(TextStyle base, AppColors colors) {
    return Caption2TextStyleBase(
      base,
      primary: base.copyWith(color: colors.display.primary),
      secondary: base.copyWith(color: colors.display.secondary),
      tertiary: base.copyWith(color: colors.display.tertiary),
      accent: base.copyWith(color: colors.accent.primary),
      danger: base.copyWith(color: colors.danger.primary),
    );
  }

  final TextStyle primary;
  final TextStyle secondary;
  final TextStyle tertiary;
  final TextStyle accent;
  final TextStyle danger;
}

class Caption2TextStyle extends Caption2TextStyleBase {
  Caption2TextStyle(
    super.base, {
    required super.primary,
    required super.secondary,
    required super.tertiary,
    required super.accent,
    required super.danger,
    required this.regular,
    required this.bold,
    required this.black,
    super.package,
  });

  factory Caption2TextStyle.generate({
    required TextStyle regular,
    required TextStyle bold,
    required TextStyle black,
    required AppColors colors,
  }) {
    return Caption2TextStyle(
      regular,
      primary: regular.copyWith(color: colors.display.primary),
      secondary: regular.copyWith(color: colors.display.secondary),
      tertiary: regular.copyWith(color: colors.display.tertiary),
      accent: regular.copyWith(color: colors.accent.primary),
      danger: regular.copyWith(color: colors.danger.primary),
      regular: Caption2TextStyleBase.generate(regular, colors),
      bold: Caption2TextStyleBase.generate(bold, colors),
      black: Caption2TextStyleBase.generate(black, colors),
    );
  }

  final Caption2TextStyleBase regular;
  final Caption2TextStyleBase bold;
  final Caption2TextStyleBase black;
}

class Caption3TextStyleBase extends BaseTextStyle {
  Caption3TextStyleBase(
    super.base, {
    required this.primary,
    required this.secondary,
    required this.tertiary,
    required this.accent,
    required this.danger,
    super.package,
  });

  factory Caption3TextStyleBase.generate(TextStyle base, AppColors colors) {
    return Caption3TextStyleBase(
      base,
      primary: base.copyWith(color: colors.display.primary),
      secondary: base.copyWith(color: colors.display.secondary),
      tertiary: base.copyWith(color: colors.display.tertiary),
      accent: base.copyWith(color: colors.accent.primary),
      danger: base.copyWith(color: colors.danger.primary),
    );
  }

  final TextStyle primary;
  final TextStyle secondary;
  final TextStyle tertiary;
  final TextStyle accent;
  final TextStyle danger;
}

class Caption3TextStyle extends Caption3TextStyleBase {
  Caption3TextStyle(
    super.base, {
    required super.primary,
    required super.secondary,
    required super.tertiary,
    required super.accent,
    required super.danger,
    required this.regular,
    required this.bold,
    required this.black,
    super.package,
  });

  factory Caption3TextStyle.generate({
    required TextStyle regular,
    required TextStyle bold,
    required TextStyle black,
    required AppColors colors,
  }) {
    return Caption3TextStyle(
      regular,
      primary: regular.copyWith(color: colors.display.primary),
      secondary: regular.copyWith(color: colors.display.secondary),
      tertiary: regular.copyWith(color: colors.display.tertiary),
      accent: regular.copyWith(color: colors.accent.primary),
      danger: regular.copyWith(color: colors.danger.primary),
      regular: Caption3TextStyleBase.generate(regular, colors),
      bold: Caption3TextStyleBase.generate(bold, colors),
      black: Caption3TextStyleBase.generate(black, colors),
    );
  }

  final Caption3TextStyleBase regular;
  final Caption3TextStyleBase bold;
  final Caption3TextStyleBase black;
}

class FootnoteTextStyleBase extends BaseTextStyle {
  FootnoteTextStyleBase(
    super.base, {
    required this.primary,
    required this.secondary,
    required this.tertiary,
    required this.accent,
    required this.danger,
    super.package,
  });

  factory FootnoteTextStyleBase.generate(TextStyle base, AppColors colors) {
    return FootnoteTextStyleBase(
      base,
      primary: base.copyWith(color: colors.display.primary),
      secondary: base.copyWith(color: colors.display.secondary),
      tertiary: base.copyWith(color: colors.display.tertiary),
      accent: base.copyWith(color: colors.accent.primary),
      danger: base.copyWith(color: colors.danger.primary),
    );
  }

  final TextStyle primary;
  final TextStyle secondary;
  final TextStyle tertiary;
  final TextStyle accent;
  final TextStyle danger;
}

class FootnoteTextStyle extends FootnoteTextStyleBase {
  FootnoteTextStyle(
    super.base, {
    required super.primary,
    required super.secondary,
    required super.tertiary,
    required super.accent,
    required super.danger,
    required this.regular,
    required this.bold,
    required this.black,
    super.package,
  });

  factory FootnoteTextStyle.generate({
    required TextStyle regular,
    required TextStyle bold,
    required TextStyle black,
    required AppColors colors,
  }) {
    return FootnoteTextStyle(
      regular,
      primary: regular.copyWith(color: colors.display.primary),
      secondary: regular.copyWith(color: colors.display.secondary),
      tertiary: regular.copyWith(color: colors.display.tertiary),
      accent: regular.copyWith(color: colors.accent.primary),
      danger: regular.copyWith(color: colors.danger.primary),
      regular: FootnoteTextStyleBase.generate(regular, colors),
      bold: FootnoteTextStyleBase.generate(bold, colors),
      black: FootnoteTextStyleBase.generate(black, colors),
    );
  }

  final FootnoteTextStyleBase regular;
  final FootnoteTextStyleBase bold;
  final FootnoteTextStyleBase black;
}

typedef AppTypography = ({
  SimpleTextStyle simple,
  BrandTextStyle brand,
  LargeTitleTextStyle largeTitle,
  Title1TextStyle title1,
  Title2TextStyle title2,
  Subtitle1TextStyle subtitle1,
  Body1TextStyle body1,
  Caption1TextStyle caption1,
  Caption2TextStyle caption2,
  Caption3TextStyle caption3,
  FootnoteTextStyle footnote,
});

class AppTypographyGenerator {
  static AppTypography generate(
    AppColors colors, {
    required TextStyle simple,
    required TextStyle brandRegular,
    required TextStyle brandBold,
    required TextStyle largeTitle,
    required TextStyle title1Regular,
    required TextStyle title1Bold,
    required TextStyle title2Regular,
    required TextStyle title2Bold,
    required TextStyle subtitle1Regular,
    required TextStyle subtitle1Bold,
    required TextStyle body1Regular,
    required TextStyle body1Bold,
    required TextStyle caption1Regular,
    required TextStyle caption1Bold,
    required TextStyle caption1Black,
    required TextStyle caption2Regular,
    required TextStyle caption2Bold,
    required TextStyle caption2Black,
    required TextStyle caption3Regular,
    required TextStyle caption3Bold,
    required TextStyle caption3Black,
    required TextStyle footnoteRegular,
    required TextStyle footnoteBold,
    required TextStyle footnoteBlack,
    TextStyle? overrides,
  }) {
    return (
      simple: SimpleTextStyle.generate(base: simple.merge(overrides), colors: colors),
      brand: BrandTextStyle.generate(
        regular: brandRegular.merge(overrides),
        bold: brandBold.merge(overrides),
        colors: colors,
      ),
      largeTitle: LargeTitleTextStyle.generate(base: largeTitle.merge(overrides), colors: colors),
      title1: Title1TextStyle.generate(
        regular: title1Regular.merge(overrides),
        bold: title1Bold.merge(overrides),
        colors: colors,
      ),
      title2: Title2TextStyle.generate(
        regular: title2Regular.merge(overrides),
        bold: title2Bold.merge(overrides),
        colors: colors,
      ),
      subtitle1: Subtitle1TextStyle.generate(
        regular: subtitle1Regular.merge(overrides),
        bold: subtitle1Bold.merge(overrides),
        colors: colors,
      ),
      body1: Body1TextStyle.generate(
        regular: body1Regular.merge(overrides),
        bold: body1Bold.merge(overrides),
        colors: colors,
      ),
      caption1: Caption1TextStyle.generate(
        regular: caption1Regular.merge(overrides),
        bold: caption1Bold.merge(overrides),
        black: caption1Black.merge(overrides),
        colors: colors,
      ),
      caption2: Caption2TextStyle.generate(
        regular: caption2Regular.merge(overrides),
        bold: caption2Bold.merge(overrides),
        black: caption2Black.merge(overrides),
        colors: colors,
      ),
      caption3: Caption3TextStyle.generate(
        regular: caption3Regular.merge(overrides),
        bold: caption3Bold.merge(overrides),
        black: caption3Black.merge(overrides),
        colors: colors,
      ),
      footnote: FootnoteTextStyle.generate(
        regular: footnoteRegular.merge(overrides),
        bold: footnoteBold.merge(overrides),
        black: footnoteBlack.merge(overrides),
        colors: colors,
      ),
    );
  }
}

typedef AppShadows = ({
  List<BoxShadow> large,
  List<BoxShadow> medium,
  List<BoxShadow> small,
});

typedef AppAnimations = ({
  AnimationStyle spatialFast,
  AnimationStyle spatialDefault,
  AnimationStyle spatialSlow,
  AnimationStyle effectFast,
  AnimationStyle effectDefault,
  AnimationStyle effectSlow,
});