name: stack_mouse_cursor
description: Utilities for working with custom mouse cursors on desktop platforms.
version: 1.0.0
publish_to: none
resolution: workspace

environment: 
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
    
  stack:
  stack_ui:
  stack_ffi:

  vector_graphics: ^1.1.19
